/**
 * Screen-chrome copy in English + Hindi (Devanagari).
 *
 * Scope is deliberate: labels, buttons, headings and helper copy switch.
 * Status words (SLA headlines, claim words, STP words) stay in English —
 * they come from @adi-vritti/ui-tokens, the shared source of truth also
 * consumed by the officer console and the Core FailureDecoder, so
 * translating them here would fork the vocabulary. Scheme names, amounts,
 * dates and IDs never translate. Brand stays "Adi-Vritti" in Latin.
 *
 * Keys are grouped by screen. Dynamic phrases are functions so plural and
 * count handling lives with the copy, not scattered across screens.
 */
export type UiLang = "en" | "hi";

export const STRINGS = {
  en: {
    loginTagline: "One student. One identity. Five schemes.",
    loginMobileLabel: "Mobile number",
    loginSendOtp: "Send OTP",
    loginDemoNote: "Demo build — enter any 10-digit number to preview. No OTP is sent in any environment.",

    homeEyebrow: "Adi-Vritti · Student",
    homeOffline: "Offline — showing cached data",
    homeDemoPreview: "Demo preview — not synced yet",
    homeSeeTimeline: "See full timeline",
    homeDoNext: "Do this next",
    homeHide: "Hide",
    homeMoney: "Money",
    homeAskAdi: "Ask Adi →",
    homeReceived: "Received",
    homeReceivedSub: "Safe in your bank",
    homePending: "Pending",
    homePendingSub: "On the way",
    homeSchemes: "My scholarships",
    homeShowAll: "Show all 5 scholarships",
    homeWhyNot: "Why not: ",
    homeMoreActions: (n: number) => `+${n} more action${n === 1 ? "" : "s"}`,
    homeEligibleLine: (n: number) => `${n} you can get · tap to see all 5`,
    greetMorning: "Good morning",
    greetAfternoon: "Good afternoon",
    greetEvening: "Good evening",

    walletEyebrow: "Verified once · reused in 5 schemes",
    walletTitle: "Document Wallet",
    walletReady: (valid: number, total: number) => `${valid} of ${total} documents ready`,
    walletStagedTitle: "DigiLocker staged (demo)",
    walletStagedSub:
      "Staged on this phone only — documents will not actually refresh. In integration this links DigiLocker via POST /v1/verify.",
    walletConnect: "Connect DigiLocker",
    walletConnecting: "Connecting…",
    walletScan: "Scan document",
    walletExplainer: "Verified once, reused across all 5 schemes until expiry. You never upload the same paper twice.",

    claimNotFound: "Document not found",
    claimGoBack: "Go back",
    claimBack: "Back",
    claimFrom: "From",
    claimVerifiedAt: "Verified",
    claimValidTill: "Valid till",
    claimDemoRefetch:
      "Demo only — refetch is staged locally, no network call. In integration this refetches the document from DigiLocker via POST /v1/verify.",
    claimRefetch: "Refetch from DigiLocker",
    claimConfused: "Still confused?",
    claimAskAdi: "Ask Adi about this document",

    appNotFound: "File not found",
    appNotFoundSub: "This application is not on your phone. Pull to sync on Home.",
    appGoBack: "Go back",
    appBack: "Back",
    appWaiting: "Waiting time",
    appWhere: "Where it is",
    appStepReceived: "Application received",
    appStepReceivedSub: "Your form reached the portal",
    appStepWith: "With: ",
    appStepDecision: "Officer decision",
    appStepDecisionSub: "Approve or ask for one fix",
    appStepPayment: "Bank payment",
    appStepPaymentSub: "Money lands in your account",
    appAskAdi: "Ask Adi about this file",

    profileEyebrow: "Student profile",
    profileIdentity: "My identity",
    profileVerified: "Verified",
    profileAadhaarSub: "Never shown in full — not even to officers",
    profileUsidSub: "One ID across all 5 schemes",
    profileAudit: "Who looked at my data",
    profileSettings: "Settings",
    profileSync: "Sync now",
    profileSyncDone: "Demo — nothing was synced (sync is not wired yet)",
    profileSyncBusy: "Syncing…",
    profileSyncIdle: "Pull the latest file status",
    profileOffline: "Keep files offline",
    profileOfflineSub: "Read status without internet",
    profileHelp: "Help & Ask Adi",
    profileSignOut: "Sign out",
    profileLanguage: "Language",
    profileLangSubEn: "App language: English · हिंदी में बदलें",
    profileLangSubHi: "ऐप की भाषा: हिन्दी · Switch to English",
  },
  hi: {
    loginTagline: "एक विद्यार्थी। एक पहचान। पाँच योजनाएँ।",
    loginMobileLabel: "मोबाइल नंबर",
    loginSendOtp: "OTP भेजें",
    loginDemoNote: "डेमो बिल्ड — झलक के लिए कोई भी 10 अंकों का नंबर डालें। किसी भी माहौल में OTP नहीं भेजा जाता।",

    homeEyebrow: "आदि-वृत्ति · छात्रा",
    homeOffline: "ऑफ़लाइन — सहेजा गया डेटा दिख रहा है",
    homeDemoPreview: "डेमो झलक — अभी सिंक नहीं हुआ",
    homeSeeTimeline: "पूरी टाइमलाइन देखें",
    homeDoNext: "आगे यह करें",
    homeHide: "छिपाएँ",
    homeMoney: "पैसे",
    homeAskAdi: "आदि से पूछें →",
    homeReceived: "मिले",
    homeReceivedSub: "आपके बैंक में सुरक्षित",
    homePending: "बाकी",
    homePendingSub: "रास्ते में",
    homeSchemes: "मेरी छात्रवृत्तियाँ",
    homeShowAll: "सभी 5 छात्रवृत्तियाँ देखें",
    homeWhyNot: "क्यों नहीं: ",
    homeMoreActions: (n: number) => `+${n} और काम`,
    homeEligibleLine: (n: number) => `${n} आपको मिल सकती हैं · सभी 5 देखने के लिए टैप करें`,
    greetMorning: "सुप्रभात",
    greetAfternoon: "नमस्कार",
    greetEvening: "शुभ संध्या",

    walletEyebrow: "एक बार सत्यापित · 5 योजनाओं में दोबारा इस्तेमाल",
    walletTitle: "दस्तावेज़ बटुआ",
    walletReady: (valid: number, total: number) => `${total} में से ${valid} दस्तावेज़ तैयार`,
    walletStagedTitle: "DigiLocker staged (डेमो)",
    walletStagedSub:
      "सिर्फ़ इस फ़ोन में staged — दस्तावेज़ असल में ताज़ा नहीं होंगे। असली ऐप में यह POST /v1/verify से DigiLocker जोड़ेगा।",
    walletConnect: "DigiLocker जोड़ें",
    walletConnecting: "जोड़ा जा रहा है…",
    walletScan: "दस्तावेज़ स्कैन करें",
    walletExplainer: "एक बार सत्यापित, expiry तक सभी 5 योजनाओं में दोबारा इस्तेमाल। एक ही काग़ज़ दोबारा कभी नहीं देना होगा।",

    claimNotFound: "दस्तावेज़ नहीं मिला",
    claimGoBack: "वापस जाएँ",
    claimBack: "वापस",
    claimFrom: "स्रोत",
    claimVerifiedAt: "सत्यापित",
    claimValidTill: "वैधता",
    claimDemoRefetch:
      "सिर्फ़ डेमो — refetch इसी फ़ोन में staged है, कोई नेटवर्क कॉल नहीं। असली ऐप में यह POST /v1/verify से दस्तावेज़ ताज़ा करेगा।",
    claimRefetch: "DigiLocker से ताज़ा करें",
    claimConfused: "अभी भी समझ नहीं आया?",
    claimAskAdi: "इस दस्तावेज़ के बारे में आदि से पूछें",

    appNotFound: "फ़ाइल नहीं मिली",
    appNotFoundSub: "यह आवेदन आपके फ़ोन में नहीं है। Home पर जाकर sync करें।",
    appGoBack: "वापस जाएँ",
    appBack: "वापस",
    appWaiting: "इंतज़ार का समय",
    appWhere: "फ़ाइल कहाँ है",
    appStepReceived: "आवेदन मिल गया",
    appStepReceivedSub: "आपका फ़ॉर्म पोर्टल पर पहुँच गया",
    appStepWith: "किसके पास: ",
    appStepDecision: "अधिकारी का फ़ैसला",
    appStepDecisionSub: "मंज़ूरी या एक सुधार",
    appStepPayment: "बैंक भुगतान",
    appStepPaymentSub: "पैसे आपके खाते में आएँगे",
    appAskAdi: "इस फ़ाइल के बारे में आदि से पूछें",

    profileEyebrow: "छात्रा प्रोफ़ाइल",
    profileIdentity: "मेरी पहचान",
    profileVerified: "सत्यापित",
    profileAadhaarSub: "पूरा कभी नहीं दिखता — अधिकारियों को भी नहीं",
    profileUsidSub: "सभी 5 योजनाओं में एक ही ID",
    profileAudit: "मेरा डेटा किसने देखा",
    profileSettings: "सेटिंग",
    profileSync: "अभी सिंक करें",
    profileSyncDone: "डेमो — कुछ सिंक नहीं हुआ (sync अभी जुड़ा नहीं है)",
    profileSyncBusy: "सिंक हो रहा है…",
    profileSyncIdle: "फ़ाइल की ताज़ा स्थिति लाएँ",
    profileOffline: "फ़ाइलें ऑफ़लाइन रखें",
    profileOfflineSub: "बिना इंटरनेट के स्थिति पढ़ें",
    profileHelp: "मदद और आदि से पूछें",
    profileSignOut: "साइन आउट",
    profileLanguage: "भाषा",
    profileLangSubEn: "App language: English · हिंदी में बदलें",
    profileLangSubHi: "ऐप की भाषा: हिन्दी · Switch to English",
  },
} as const;

export type Strings = (typeof STRINGS)["en"] | (typeof STRINGS)["hi"];
